# Generated by Django 4.2.18 on 2025-01-15 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapist_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistprofile',
            name='availability',
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='credentials',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='photo',
            field=models.ImageField(blank=True, default=2, upload_to='profile_pics/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='therapist_profiles.therapistprofile')),
            ],
        ),
    ]
