# Generated by Django 4.2.18 on 2025-01-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist_profiles', '0003_service_alter_therapistprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='credentials',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='services',
            field=models.ManyToManyField(related_name='therapists', to='therapist_profiles.service'),
        ),
    ]
