# Generated by Django 4.2.18 on 2025-01-16 11:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapist_profiles', '0004_alter_therapistprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistprofile',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
